# Generated by Selenium IDE
# import pytest
# import time
# import json
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

DRIVER_PATH = '/path/to/chromedriver'

options = Options()
options.add_argument("--window-size=1920,1200")
options.add_argument("--headless")
driver = webdriver.Chrome(executable_path=DRIVER_PATH)
driver.get("https://git.iptp.net/xm/xm-web/-/issues/?sort=updated_desc&state=opened&label_name%5B%5D=Need%20to%20test&first_page_size=20")
# options.headless = True
# print(driver.page_source)
driver.quit()
content = driver.findElements(By.xpath("//div[@class='issuable-list-container']/ul/li"))
print(content)



class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
    self.options = Options()
    self.options.headless = True
    self.options.add_argument("--window-size=1920,1200")
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def find_element(self):
    content = self.driver.findElements(By.xpath("//div[@class='issuable-list-container']/ul/li"))
    print(content)

  
  def test_untitled(self):
    self.driver.get("https://git.iptp.net/xm/xm-web/-/issues/?sort=updated_desc&state=opened&label_name%5B%5D=Need%20to%20test&first_page_size=20")
    print(self.driver.page_source)
    self.driver.quit()
  
