# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import os
from dotenv import load_dotenv


try:
  load_dotenv()
  GITLAB_USERNAME = os.environ["GITLAB_USERNAME"]
  GITLAB_PASSWORD = os.environ["GITLAB_PASSWORD"]
  # print("Environment variable>>> ", GITLAB_USERNAME, GITLAB_PASSWORD)

except KeyError:
  print("Environment variable does not exist", KeyError)


class TestGitlabsignin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
    print("1")
  
  def teardown_method(self, method):
    self.driver.quit()
    print("3nd")
  
  def find_element(self):
    delay = 10 # seconds
    elem = WebDriverWait(self.driver, delay).until(self.driver.find_element(By.XPATH, '//*[@class="content-list issuable-list issues-list"]/li'))
    # content = self.driver.find_element(By.CLASS_NAME, "//content-list issuable-list issues-list")
    i = 1
    for x in elem:
      i += 1
      print(">>>>i: ", i)

      # tag_a = self.driver.find_element(By.XPATH, "//a[@class='gl-link issue-title-text']")
      # url = tag_a.get_attribute("href")
      # txt = tag_a.get_attribute("text")
      # print(">>>>Url: ", url)
      # print(">>>>Text: ", txt)
      # iss_number = url[url.rfind("/"):]
      # print(">>>>iss Number: ", iss_number)
      # self.driver.get(url)

  def test_gitlabsignin(self):
    print("2")
    self.driver.get("https://git.iptp.net/users/sign_in")
    self.driver.set_window_size(1047, 652)
    self.driver.find_element(By.ID, "user_login").send_keys(GITLAB_USERNAME)
    self.driver.find_element(By.ID, "user_password").send_keys(GITLAB_PASSWORD)
    submit_ele = self.driver.find_element(By.XPATH, "//button[@type='submit']")
    print(">>", submit_ele)
    submit_ele.click()
    self.driver.get("https://git.iptp.net/xm/xm-web/-/issues/?sort=updated_desc&state=opened&label_name%5B%5D=Need%20to%20test&first_page_size=20")
    self.find_element()
    self.driver.close()

  # def test_gitlabsignin2(self):
  #   print("3")
  #   self.driver.get("https://git.iptp.net/xm/xm-web/-/issues/?sort=updated_desc&state=opened&label_name%5B%5D=Need%20to%20test&first_page_size=20")
  #   self.driver.set_window_size(1047, 652)
  #   # print(">>", submit_ele)
  #   # submit_ele.click()
  #   self.driver.close()
  